### ISSUE TITLE
Audio is working?

### ISSUE THREAD

**Issue by thienpow** [android-raspi/android_device_broadcom_rpi3#1]
Sir, is this build come with a working audio?

**Comment by humberos** [comment]
I am sorry.
Although the build should be ok but I haven't had free time to test it yet.

**Comment by thienpow** [comment]
TQ Sir.  I will try to test it on this weekend...  

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.
